language: go

go:
  - 1.12
  - tip

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

services:
  - docker

env:
  global:
    - GO111MODULE=on

script:
  - make test-coverage
  # TODO(#19): migrate to src-d/ci, use 'make test'

after_success:
  - bash <(curl -s https://codecov.io/bash)

# TODO(#19): migrate to src-d/ci, add separate release stage
